rootProject.name = "code-challenges"

include("challenges:wc")
include("challenges:json-parser")
include("challenges:compression-tool")
include("challenges:cut-tool")
include("challenges:load-balancer")
include("challenges:sort-tool")
include("challenges:calculator")
include("challenges:redis-server")
include("challenges:grep")
include("challenges:uniq")
include("challenges:web-server")
include("challenges:url-shortener")
include("challenges:diff")
include("challenges:shell")
include("challenges:cat")
include("challenges:irc-client")
